### ISSUE TITLE
[models] app model

### ISSUE THREAD

**Issue by Jma353** [cuappdev/register#2]
Each `app` will own many `event_types`.  Other metadata includes `name`, `creator` (can be a string for now), and `secret_key` (URL-safe base64 random token) etc.  If you can think of more relevant fields, by all means add them. 

For the `secret_key`, this line of code should do the trick in generating one: 

```python
hashlib.sha1(os.urandom(64)).hexdigest()
```

**Comment by young-k** [comment]
merge sha: 6ea49b92788ede3c03d15b18fb1e5571dad65c43
