### ISSUE TITLE
[models] event_type model

### ISSUE THREAD

**Issue by Jma353** [cuappdev/register#3]
Each `event_type` will be owned by one `app`, so a foreign key / relationship in `SQLAlchemy` will be necessary.  The `event_type` should have a `creator` field (string for now), as well as a `name` field.  The `event_type` should have some sort of `JSON blob` field called `fields_info` with mappings from the custom fields of the event to constraints.  For example, an event called `PodcastSearchEvent`: 

```
{
  searched_term: { 
    type: string, 
    required: true
  },
  user_id: {
    type: int,
    required: false,
    default: -1
  }
}
```

Note the above constraints.  `type` will indicate the data-type.  `default` will indicate the placeholder to be filled in if no value is given for that particular field.  `required` will indicate whether the user must fill in the field or not; if this is `true`, then the `default` constraint is not required.  

Note the above is `NOT` exhaustive of what would be stored in the actual event of that particular `event_type`.  Other fields would exist in the event such as `created_at`, `message`, etc.

**Comment by young-k** [comment]
559ee6c0ca916caa1d4bd14f18b6128e99b56c0f
