### ISSUE TITLE
[server] events missing timestamps

### ISSUE THREAD

**Issue by xaanimus** [cuappdev/register#51]
The server doesn't return timestamps when events are sent.

After POSTing to `/api/events/create/`
```
{
	"events": [
		{
			"event_type": "searchBarTapped",
			"payload": {
				"location": "testLocation"
			},
			"timestamp": "2017-12-29 20:41:10 GMT"
		}
	]
}
```
with headers
`Authorization = Bearer <secret key>`
`Content-Type = application/json`

The server returns the event with a null timestamp:

```
{
    "data": {
        "failed": [],
        "succeeded": [
            {
                "event_type": "searchBarTapped",
                "id": 39,
                "payload": {
                    "location": "testLocation"
                },
                "timestamp": null
            }
        ]
    },
    "success": true
}
```

Querying for events with `/api/apps/2/events/` also contains null timestamps. The same thing happens after removing `GMT` from the sent timestamp.

**Comment by kq-li** [comment]
Will take a look, thanks for the heads up!

**Comment by xaanimus** [comment]
👍🏿
